### PR TITLE
Strip illegal characters from paths

### PR DESCRIPTION
**Pull request by keppo070**
regexp to change windows reserved characters into an underscore

### CODE REVIEW

**Comment by keppo070** [comment]
https://github.com/Anthirian/script.service.janitor/issues/74#issue-392300564
this is one is also related to it 
https://github.com/Anthirian/script.service.janitor/issues/78#issue-493759328

This is what I'm resolving. Its a quick fix. Not very nice but i'm not a programmer.

**Comment by Anthirian** [comment]
Oh right I forgot all about that. So what you're actually saying is that `makeLegalFilename` from the `xbmc` module does not strip the `:` from movie titles before Janitor moves the file to a location based on the movie title? If that is the case then this could indeed serve as a workaround. 

It also doesn't make much sense to file a bug report to the Kodi team about this, [considering that the method has been changed in Kodi 19](https://codedocs.xyz/xbmc/xbmc/group__python__xbmcvfs.html#gac40e0ecd5b1aa66a90c5c0918cd40491).

**Comment by keppo070** [comment]
If I recall right. It didn't work on the folder. So it would fail. That's why I changes it way up there. A json file would be created but that was not right.

I agree that a bug report would not be helpful. when will the new method implementedin janitor

**Comment by Anthirian** [comment]
Okay then I'll merge it now and when Kodi Matrix is released I need to rework large parts of Janitor anyway. That is also the perfect time to include the new `makeLegalPath` in the code. Currently I don't have a way to test Janitor on a version that has Python 3 support, so this is the best I can do for now.

Thanks for contributing.

**Pull request merged**
